### ISSUE TITLE
Blacklist Vehicles

### ISSUE THREAD

**Issue by Brutuss** [Blumlaut/anticheese-anticheat#22]
Hi! First of all nice script! It works great. But I don't seem to get the blacklisted vehicles to work. 

I have changed in the config: 

`["client.carblacklist"] = true, -- blacklist certain cars in ac_c.lua`

and 

```
-- list of cars that cannot be spawned
blacklistedCars = {
	`khanjali`,
	`blista`,
}
```

When spawning both vehicles nothing happens. They spawn and you can drive with them.

When I spawn a weapon that is blacklisted I gets removed. So the script is working.

**Comment by zRxnx** [comment]
come on the discord for better and faster help https://discord.gg/EffffYJG
