### ISSUE TITLE
False positive on clearing tasks

### ISSUE THREAD

**Issue by kc1nn4y** [Blumlaut/anticheese-anticheat#26]
Multiple people have been banned on my server for the clearing ped tasks detection.
However, I know that these individuals do not use any form of cheating software.
Why is this still being triggered?

**Comment by Robi321** [comment]
I will soon

**Comment by Robi321** [comment]
@kc1nn4y what framework do you use?

**Comment by MaximusR9** [comment]
@Robi321 One of my co-owners got banned for using the Drag function in aot_piggyback script.

This might help:
`RegisterNetEvent('esx_barbie_lyftupp:upplyft')
AddEventHandler('esx_barbie_lyftupp:upplyft', function(target)
	local playerPed = GetPlayerPed(-1)
	local targetPed = GetPlayerPed(GetPlayerFromServerId(target))
	local lPed = GetPlayerPed(-1)
	local dict = "amb@code_human_in_car_idles@low@ps@"
	
	if isCarry == false then
		LoadAnimationDictionary("amb@code_human_in_car_idles@generic@ps@base")
		TaskPlayAnim(lPed, "amb@code_human_in_car_idles@generic@ps@base", "base", 8.0, -8, -1, 33, 0, 0, 40, 0)
		
		AttachEntityToEntity(GetPlayerPed(-1), targetPed, 9816, 0.015, 0.38, 0.11, 0.9, 0.30, 90.0, false, false, false, false, 2, false)
		
		isCarry = true
		IsLiftup = true
	else
		DetachEntity(GetPlayerPed(-1), true, false)
		ClearPedTasksImmediately(targetPed)
		ClearPedTasksImmediately(GetPlayerPed(-1))
		
		IsLiftup = false
		isCarry = false
	end
end)`

I think ClearPedTasksImmediately is causing the false detection but I'm not sure.

This is what's shown in the discord webhook logs:
https://i.imgur.com/Q12vMEA.png

**Comment by Robi321** [comment]
Thanks I will fix it.

**Comment by Robi321** [comment]
@MaximusR9 ClearPedTasksImmediately it is needed in your script so I recommend that you simply disable this function in anticheat
