### ISSUE TITLE
Anti-cheat false positives on spectating players

### ISSUE THREAD

**Issue by MaximusR9** [Blumlaut/anticheese-anticheat#29]
Hi so I'm a main dev of one of the servers where we have installed this anticheat and spectating players gives this warning in discord

[https://i.imgur.com/IDwSE3n.png](https://i.imgur.com/IDwSE3n.png)

after 3 or 4 strikes we get banned.

I'm using EasyAdmin spectate function which is supposed to work correctly with this anticheat

**Comment by Blumlaut** [comment]
https://github.com/Blumlaut/anticheese-anticheat/blob/master/ac_config.lua#L13

https://github.com/Blumlaut/anticheese-anticheat#bypass-checks

**Comment by MaximusR9** [comment]
Oh that's why I thought I already added the bypass ace but it seems to be missing from server.cfg
