### ISSUE TITLE
Anticheese stops flatbed script from working

### ISSUE THREAD

**Issue by ChickenDipper1** [Blumlaut/anticheese-anticheat#40]
Describe the issue
Anticheat causing error message when lowering flatbed bed from this script: (https://github.com/TinusNL/tinus_flatbed)

Attempted Solutions
Disable all Anticheese options under: -- these MIGHT trigger in legitimate circumstances, beware before enabling

Screenshots/Logs
![image](https://user-images.githubusercontent.com/41157940/203511157-aa1d6351-9919-4086-ab2a-a2e57a501494.png)

Server Infos (please complete the following information):

OS: Windows Server 2019
FXServer Version 5949
EasyAdmin Version 6.91
Additional context
Disabling Anticheese allows the script to work correctly, do you know if it is possible to make the flatbed script work with Anticheese?
Thank you.

**Comment by Blumlaut** [comment]
8839120d is FIND_NEXT_VEHICLE, do you have `server.blockClientEntities` enabled? not sure what else would cause this.

**Comment by ChickenDipper1** [comment]
I don't have that setting enabled, thanks for coming back to me.
I have removed the flatbed for now if it is not possible to work with anticheese.

**Comment by Blumlaut** [comment]
i doubt this is an issue even related to anticheese, nothing ac does would block FindNextVehicle as far as i can tell.

**Comment by ChickenDipper1** [comment]
It works fine without anticheese, no issues at all. #weird
